# vim: set ts=2:sw=2:et :
version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: "${GITLAB_CE_HOSTNAME}"
    container_name: gitlab
    volumes:
      - etc:/etc/gitlab
      - data:/var/opt/gitlab
    shm_size: '256m'
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host(`${GITLAB_CE_HOSTNAME}`)
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.routers.gitlab.tls.certresolver=leresolver
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.tcp.routers.tcpgitlab.rule=HostSNI(`*`)
      - traefik.tcp.routers.tcpgitlab.entrypoints=ssh
      - traefik.tcp.routers.tcpgitlab.service=tcpgitlab
      - traefik.tcp.services.tcpgitlab.loadbalancer.server.port=22

networks:
  default:
    external: true
    name: main-network
   
volumes:
  etc:
  data: 
