# vim: set ts=2:sw=2:et :
version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: "${GITLAB_CE_HOSTNAME}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${GITLAB_CE_HOSTNAME}"
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - etc:/etc/gitlab
      - data:/var/opt/gitlab
    shm_size: '256m'
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host(`${GITLAB_CE_HOSTNAME}`)
      - traefik.http.routers.gitlab.entrypoints=websecure,ssh
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.routers.gitlab.tls.certresolver=leresolver
      - traefik.http.services.gitlab.loadbalancer.server.port=443

volumes:
  etc:
  data: 

networks:
  default:
    external: true
    name: portainer-stack_default
